# Generated by Django 5.2.11 on 2026-03-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='mobile',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
